#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

mkdir -p $OPENSHIFT_LOG_DIR/httpd
mkdir -p $OPENSHIFT_DATA_DIR/docroot

rm -rf $OPENSHIFT_DATA_DIR/etc
rm -rf $OPENSHIFT_DATA_DIR/var

cp -r $OPENSHIFT_REPO_DIR/etc $OPENSHIFT_DATA_DIR/
cp -r $OPENSHIFT_REPO_DIR/var $OPENSHIFT_DATA_DIR/

ln -s /usr/lib64/httpd/modules $OPENSHIFT_REPO_DIR/modules

mkdir -p $OPENSHIFT_LOG_DIR/mlogc

sed -i 's/COLLECTOR_ROOT/'$OPENSHIFT_LOG_DIR'/g' $OPENSHIFT_DATA_DIR/etc/mlogc.conf

sed -i 's/INTERNAL_IP/'$OPENSHIFT_INTERNAL_IP'/g' $OPENSHIFT_DATA_DIR/etc/mlogc.conf
