#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

cp -r $OPENSHIFT_REPO_DIR/etc $OPENSHIFT_DATA_DIR/

ln -s /usr/lib64/httpd/modules $OPENSHIFT_REPO_DIR/modules

