#!/bin/bash
# The logic to stop your application should be put in this script.
kill `cat $OPENSHIFT_RUNTIME_DIR/httpd.pid` > /dev/null 2>&1
kill `ps -ef | grep mlogc | awk '{ print $2 }'` > /dev/null 2>&1
exit 0
